version: '3.7'

services:
  postgresql:
    build: 
      context: ./postgresql
    restart: always  
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: 'postgresql'
      POSTGRES_DB: 'news'
